//
// Generated file, do not edit! Created by opp_msgc 4.1 from QoSMessage.msg.
//

#ifndef _QOSMESSAGE_M_H_
#define _QOSMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>QoSMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet QoSMessage {
 *     string from;
 *     string to;
 *     unsigned long seqCount;
 * }
 * </pre>
 */
class QoSMessage : public ::cPacket
{
  protected:
    opp_string from_var;
    opp_string to_var;
    unsigned long seqCount_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QoSMessage&);

  public:
    QoSMessage(const char *name=NULL, int kind=0);
    QoSMessage(const QoSMessage& other);
    virtual ~QoSMessage();
    QoSMessage& operator=(const QoSMessage& other);
    virtual QoSMessage *dup() const {return new QoSMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getFrom() const;
    virtual void setFrom(const char * from_var);
    virtual const char * getTo() const;
    virtual void setTo(const char * to_var);
    virtual unsigned long getSeqCount() const;
    virtual void setSeqCount(unsigned long seqCount_var);
};

inline void doPacking(cCommBuffer *b, QoSMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, QoSMessage& obj) {obj.parsimUnpack(b);}


#endif // _QOSMESSAGE_M_H_
