//
// Generated file, do not edit! Created by opp_msgc 4.1 from QueueControllerMessage.msg.
//

#ifndef _QUEUECONTROLLERMESSAGE_M_H_
#define _QUEUECONTROLLERMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>QueueControllerMessage.msg</tt> by opp_msgc.
 * <pre>
 * message QueueControllerMessage {
 *     double load;
 *     double windowTime;
 * }
 * </pre>
 */
class QueueControllerMessage : public ::cMessage
{
  protected:
    double load_var;
    double windowTime_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const QueueControllerMessage&);

  public:
    QueueControllerMessage(const char *name=NULL, int kind=0);
    QueueControllerMessage(const QueueControllerMessage& other);
    virtual ~QueueControllerMessage();
    QueueControllerMessage& operator=(const QueueControllerMessage& other);
    virtual QueueControllerMessage *dup() const {return new QueueControllerMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getLoad() const;
    virtual void setLoad(double load_var);
    virtual double getWindowTime() const;
    virtual void setWindowTime(double windowTime_var);
};

inline void doPacking(cCommBuffer *b, QueueControllerMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, QueueControllerMessage& obj) {obj.parsimUnpack(b);}


#endif // _QUEUECONTROLLERMESSAGE_M_H_
